#ifndef INTERRUPT_STACK_FRAME_H
#define INTERRUPT_STACK_FRAME_H

#include <kernel.h>
typedef struct
{
    ULONGLONG DR0;
    ULONGLONG DR1;
    ULONGLONG DR2;
    ULONGLONG DR3;
    ULONGLONG DR4;
    ULONGLONG DR5;
    ULONGLONG DR6;
    ULONGLONG DR7;
    ULONGLONG CR0;
    ULONGLONG CR2;
    ULONGLONG CR3;
    ULONGLONG CR4;
    ULONGLONG CR8;
    ULONGLONG GS;
    ULONGLONG FS;
    ULONGLONG ES;
    ULONGLONG DS;
    ULONGLONG R15;
    ULONGLONG R14;
    ULONGLONG R13;
    ULONGLONG R12;
    ULONGLONG R11;
    ULONGLONG R10;
    ULONGLONG R9;
    ULONGLONG R8;
    ULONGLONG RDI;
    ULONGLONG RSI;
    ULONGLONG RBP;
    ULONGLONG RSP;
    ULONGLONG RDX;
    ULONGLONG RCX;
    ULONGLONG RBX;
    ULONGLONG RAX;
    ULONGLONG InterruptNumber;
    ULONGLONG ErrorCode;
    ULONGLONG RIP;
    ULONGLONG CS;
    ULONGLONG RFLAGS;
    ULONGLONG OriginalRSP;
    ULONGLONG SS;
} __attribute__((packed)) INTERRUPT_STACK_FRAME;

#endif // INTERRUPT_STACK_FRAME_H